# Generated by Django 4.2.8 on 2024-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('100', 'Заявка не подана'), ('200', 'В обработке'), ('300', 'Заявка одобрена'), ('400', 'Заявка удалена')], default='200', max_length=3, verbose_name='Статус'),
        ),
    ]
