# Generated by Django 4.2.8 on 2024-02-09 14:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default=0, upload_to=main.models.file_directory_path, verbose_name='Фото артиста'),
            preserve_default=False,
        ),
    ]
